# This is a basic workflow to help you get started with Actions

name: surgereactapp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setting up Node JS environment
        uses: actions/setup-node@1.4.2
        with:
          version: 12
                        
      # Runs a set of commands using the runners shell
      - name: Installing Node modules
        run: npm install
        
      # Runs a set of commands using the runners shell
      - name: Build npm
        run: npm build
      
      # Runs a set of commands using the runners shell
      - name: Installing Surge modules
        run: npm install --global surge
      
     # Runs a set of commands using the runners shell
      - name: Configuring Surge with SSH keys
        run: surge ./build http://b20reactapp.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
